[package]
name = "bloda"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.6", features = ["sqlite"] }
lz4_flex = "0.11.3"
rayon = "1.10.0"
regex = "1.11.1"
rust-lzma = { version = "0.6.0", features = ["static"] }
walkdir = "2.5.0"
zstd = "0.13.2"
